server:
  port: 8010
user:
  userServiceUrl: http://localhost:8080/
eureka:
  client:
    healthcheck:
          enabled: true
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-consumer-movie
logging:
  level:
    com.pl.microservicesimpleconsumermovie.SERVICE.UserFeignClient: DEBUG