server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/LeonPang/spring-cloud-config-repo
#          uri: https://gitee.com/LeonPang/{application}
          username: 106176354@qq.com
          password: 9977205
