server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
#zuul:
#  ignored-services: '*'
#  routes:
#    microservice-provider-user: /user/**
logging:
  level:
    com.netflix: DEBUG
zuul:
  max:
    host:
      connections: 5000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000


