server:
  port: 8084
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: microservice-provider-user
#  zipkin:
#    base-url: http://localhost:9411
  kafka:
      bootstrap-servers: localhost:9092
      client-id: asd4
      consumer:
        enable-auto-commit: true
        group-id: asdasd4
  sleuth:
    sampler:
      percentage: 1.0 #1.0是100%的意思
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.web.servlet.DispatcherServlet: DEBUG
#info:
#  app:
#    name: @project.artifactId@
#    encoding: @project.build.sourceEncoding@
#    java:
#      source: @java.version@
#      target: @java.version@
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: asdasd
